# Site settings
title: "TestCafe Studio"
baseurl: "" 
url: "http://testcafe-studio.devexpress.com" 
  
# Build settings
markdown: redcarpet
highlighter: null
redcarpet:
  extensions: ["tables"]
plugins:
  - jekyll-sitemap

# Blog
excerpt_separator: "<!--more-->"